import { Link } from "react-router-dom";
import { ArrowUpRight } from "lucide-react";
import { motion } from "framer-motion";

const collections = [
  { id:1, eyebrow:"01 · Everyday", title:"Signature Rings", image:"https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1400&auto=format&fit=crop", link:"/shop?category=rings" },
  { id:2, eyebrow:"02 · Statement", title:"Modern Necklaces", image:"https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1400&auto=format&fit=crop", link:"/shop?category=necklaces" },
  { id:3, eyebrow:"03 · Occasion", title:"Celebration Edit", image:"https://images.unsplash.com/photo-1611652022419-a9419f74343d?q=80&w=1400&auto=format&fit=crop", link:"/shop?category=earrings" },
];
export default function Collections(){return <section className="bg-white py-20 sm:py-24 lg:py-28"><div className="mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-10"><div className="mb-12 max-w-2xl"><span className="text-[10px] font-bold uppercase tracking-[.3em] text-[#6594B1]">Shop the edit</span><h2 className="mt-4 font-heading text-4xl font-semibold text-[#213C51] sm:text-5xl">Find the piece that feels like you.</h2><p className="mt-4 text-sm leading-7 text-slate-500 sm:text-base">Three carefully composed edits, one signature language of modern silver.</p></div><div className="grid gap-5 md:grid-cols-3">{collections.map((item,index)=><motion.div key={item.id} initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.55,delay:index*.08}}><Link to={item.link} className="group relative block aspect-[.82] overflow-hidden rounded-[30px] bg-[#213C51]"><img src={item.image} alt={item.title} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105 group-hover:rotate-[.5deg]"/><div className="absolute inset-0 bg-gradient-to-t from-[#213C51]/85 via-[#213C51]/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 sm:p-7"><span className="text-[10px] font-semibold uppercase tracking-[.22em] text-white/70">{item.eyebrow}</span><h3 className="mt-2 font-heading text-3xl text-white">{item.title}</h3><span className="mt-5 inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-4 py-2 text-xs font-semibold text-white backdrop-blur-md transition group-hover:bg-white group-hover:text-[#213C51]">Explore <ArrowUpRight size={14}/></span></div></Link></motion.div>)}</div></div></section>}
