import { useEffect, useMemo, useState } from "react";
import { SlidersHorizontal, X, ChevronDown, Search, Sparkles } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import ProductCard from "../components/product/ProductCard";
import Loader from "../components/common/Loader";
import EmptyState from "../components/common/EmptyState";
import { getProducts } from "../api/product.api";
import { getCategories } from "../api/category.api";
import { useSearch } from "../context/SearchContext";

const SORTS = [["newest","Newest"],["price-low","Price: Low to High"],["price-high","Price: High to Low"],["name","Name: A–Z"]];
const GENDERS = [["all","All"],["men","Men"],["women","Women"],["kids","Kids"],["unisex","Unisex"]];

export default function Shop() {
  const [searchParams,setSearchParams]=useSearchParams();
  const {query}=useSearch();
  const [products,setProducts]=useState([]), [categoryList,setCategoryList]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState("");
  const [drawer,setDrawer]=useState(false);
  const [sort,setSort]=useState(searchParams.get("sort")||"newest");
  const [gender,setGender]=useState(searchParams.get("gender")||"all");
  const [category,setCategory]=useState(searchParams.get("category")||"all");
  const [minPrice,setMinPrice]=useState(searchParams.get("minPrice")||"");
  const [maxPrice,setMaxPrice]=useState(searchParams.get("maxPrice")||"");
  const currentPage=Math.max(Number(searchParams.get("page"))||1,1);
  const searchQuery=searchParams.get("search") ?? query ?? "";

  useEffect(()=>{setSort(searchParams.get("sort")||"newest");setGender(searchParams.get("gender")||"all");setCategory(searchParams.get("category")||"all");setMinPrice(searchParams.get("minPrice")||"");setMaxPrice(searchParams.get("maxPrice")||"");},[searchParams]);

  useEffect(()=>{let cancelled=false;(async()=>{try{const r=await getCategories();const d=r?.data?.data;const list=Array.isArray(d)?d:Array.isArray(d?.categories)?d.categories:Array.isArray(d?.docs)?d.docs:[];if(!cancelled)setCategoryList(list.filter(c=>c?.isDeleted!==true&&c?.isActive!==false));}catch{if(!cancelled)setCategoryList([]);}})();return()=>{cancelled=true}},[]);

  useEffect(()=>{let cancelled=false;(async()=>{setLoading(true);setError("");try{const p={page:currentPage,limit:24};if(searchQuery.trim())p.search=searchQuery.trim();if(gender!=="all")p.gender=({men:"Men",women:"Women",kids:"Kids",unisex:"Unisex"})[gender]||gender;const cat=categoryList.find(c=>c?._id===category||c?.slug===category||c?.name?.toLowerCase()===category.toLowerCase());if(category!=="all")p.category=cat?.name||category;if(minPrice)p.minPrice=Number(minPrice);if(maxPrice)p.maxPrice=Number(maxPrice);if(sort&&sort!=="newest")p.sort=sort;const r=await getProducts(p);const d=r?.data?.data;if(!cancelled){setProducts(Array.isArray(d?.products)?d.products:[]);setPagination(d?.pagination||{});}}catch(e){if(!cancelled){setProducts([]);setError(e?.response?.data?.message||"Unable to load products. Please try again.");}}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[currentPage,searchQuery,gender,category,minPrice,maxPrice,sort,categoryList]);
  const [pagination,setPagination]=useState({total:0,totalPages:0,hasNextPage:false,hasPrevPage:false});
  const categories=useMemo(()=>[{_id:"all",slug:"all",name:"All Categories"},...categoryList],[categoryList]);
  const apply=()=>{const p=new URLSearchParams(searchParams);[["gender",gender],["category",category],["sort",sort],["minPrice",minPrice],["maxPrice",maxPrice]].forEach(([k,v])=>v&&v!=="all"?p.set(k,v):p.delete(k));searchQuery.trim()?p.set("search",searchQuery.trim()):p.delete("search");p.delete("page");setSearchParams(p);setDrawer(false)};
  const clear=()=>{setGender("all");setCategory("all");setSort("newest");setMinPrice("");setMaxPrice("");const p=new URLSearchParams(searchQuery.trim()?{search:searchQuery.trim()}:{});setSearchParams(p);setDrawer(false)};
  const go=(page)=>{const p=new URLSearchParams(searchParams);page<=1?p.delete("page"):p.set("page",String(page));setSearchParams(p);window.scrollTo({top:0,behavior:"smooth"})};

  if(loading)return <Loader/>;
  return <div className="min-h-screen bg-[#FAFAFA] pb-24">
    <div className="border-b border-[#213C51]/8 bg-white"><div className="mx-auto max-w-7xl px-4 py-8 sm:py-10"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.28em] text-[#6594B1]">Madan Gold · 925 Silver</p><h1 className="mt-2 text-3xl sm:text-5xl">{searchQuery.trim()?`Search results for “${searchQuery}”`:"Shop Jewellery"}</h1><p className="mt-2 text-sm text-slate-500">{pagination.total||0} live products from your inventory.</p></div><button onClick={()=>setDrawer(true)} className="flex h-11 items-center justify-center gap-2 rounded-full border border-[#213C51]/15 bg-white px-5 text-sm font-semibold text-[#213C51] shadow-sm md:hidden"><SlidersHorizontal size={17}/> Filters & Sort</button></div></div></div>
    <div className="sticky top-[68px] z-30 hidden border-b border-[#213C51]/8 bg-white/95 backdrop-blur-xl md:block"><div className="mx-auto flex max-w-7xl items-center gap-3 overflow-x-auto px-4 py-3"><div className="flex shrink-0 items-center gap-2 text-xs font-bold uppercase tracking-[.15em] text-slate-400"><SlidersHorizontal size={15}/> Filters</div>{GENDERS.map(([v,l])=><button key={v} onClick={()=>{setGender(v);const p=new URLSearchParams(searchParams);v==="all"?p.delete("gender"):p.set("gender",v);p.delete("page");setSearchParams(p)}} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${gender===v?"bg-[#213C51] text-white":"bg-[#EEEEEE] text-[#213C51]"}`}>{l}</button>)}<select value={category} onChange={e=>{setCategory(e.target.value);const p=new URLSearchParams(searchParams);e.target.value==="all"?p.delete("category"):p.set("category",e.target.value);p.delete("page");setSearchParams(p)}} className="h-9 rounded-full border border-[#213C51]/10 bg-white px-4 text-xs font-semibold text-[#213C51]"><option value="all">All categories</option>{categoryList.map(c=><option key={c._id} value={c.slug||c.name?.toLowerCase()}>{c.name}</option>)}</select><div className="ml-auto flex shrink-0 items-center gap-2"><span className="text-xs text-slate-400">Sort</span><select value={sort} onChange={e=>{setSort(e.target.value);const p=new URLSearchParams(searchParams);p.set("sort",e.target.value);p.delete("page");setSearchParams(p)}} className="h-9 rounded-full border border-[#213C51]/10 bg-white px-4 text-xs font-semibold text-[#213C51]">{SORTS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div></div>
    <main className="mx-auto max-w-7xl px-4 py-7 sm:py-10">{error&&<div className="mb-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{products.length===0?<EmptyState title="No Products Found" subtitle={searchQuery.trim()?"Try another search or remove a filter.":"Products will appear here when they are available in your live inventory."}/>:<><div className="grid grid-cols-2 gap-3 sm:gap-5 lg:grid-cols-4">{products.map(p=><ProductCard key={p._id} product={p}/>)}</div>{pagination.totalPages>1&&<div className="mt-10 flex items-center justify-center gap-3"><button disabled={!pagination.hasPrevPage} onClick={()=>go(currentPage-1)} className="rounded-full border bg-white px-5 py-2.5 text-sm disabled:opacity-40">Previous</button><span className="text-sm text-slate-500">{pagination.page||currentPage} / {pagination.totalPages}</span><button disabled={!pagination.hasNextPage} onClick={()=>go(currentPage+1)} className="rounded-full bg-[#213C51] px-5 py-2.5 text-sm text-white disabled:opacity-40">Next</button></div>}</>}</main>
    <div className="fixed inset-x-0 bottom-0 z-40 border-t border-[#213C51]/10 bg-white/95 p-3 shadow-[0_-10px_30px_rgba(33,60,81,.08)] backdrop-blur-xl md:hidden"><button onClick={()=>setDrawer(true)} className="flex h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#213C51] text-sm font-semibold text-white"><SlidersHorizontal size={17}/> Filters & Sort {pagination.total?`· ${pagination.total}`:""}</button></div>
    {drawer&&<div className="fixed inset-0 z-[140] bg-[#213C51]/40 backdrop-blur-sm md:hidden" onClick={()=>setDrawer(false)}><aside onClick={e=>e.stopPropagation()} className="absolute bottom-0 left-0 right-0 max-h-[85vh] overflow-y-auto rounded-t-[28px] bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#6594B1]">Refine</p><h2 className="mt-1 text-2xl">Shop filters</h2></div><button onClick={()=>setDrawer(false)} className="rounded-full bg-[#EEEEEE] p-2"><X size={18}/></button></div><div className="mt-6 space-y-6"><div><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">Gender</label><div className="flex flex-wrap gap-2">{GENDERS.map(([v,l])=><button key={v} onClick={()=>setGender(v)} className={`rounded-full px-4 py-2 text-xs font-semibold ${gender===v?"bg-[#213C51] text-white":"bg-[#EEEEEE] text-[#213C51]"}`}>{l}</button>)}</div></div><div><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">Category</label><select value={category} onChange={e=>setCategory(e.target.value)} className="h-12 w-full rounded-2xl border border-slate-200 px-4 text-sm">{categories.map(c=><option key={c._id} value={c.slug||c._id}>{c.name}</option>)}</select></div><div><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">Price range</label><div className="grid grid-cols-2 gap-3"><input value={minPrice} onChange={e=>setMinPrice(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="Min ₹" className="h-12 rounded-2xl border border-slate-200 px-4"/><input value={maxPrice} onChange={e=>setMaxPrice(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="Max ₹" className="h-12 rounded-2xl border border-slate-200 px-4"/></div></div><div><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-slate-400">Sort by</label><select value={sort} onChange={e=>setSort(e.target.value)} className="h-12 w-full rounded-2xl border border-slate-200 px-4 text-sm">{SORTS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="flex gap-3"><button onClick={clear} className="h-12 flex-1 rounded-2xl border border-slate-200 font-semibold">Clear</button><button onClick={apply} className="h-12 flex-[2] rounded-2xl bg-[#213C51] font-semibold text-white">Apply filters</button></div></div></aside></div>}
  </div>;
}
