
import request from "supertest";
import app from "../../src/app.js";

describe("Customer Login", () => {
  test("Login Customer", async () => {
    const unique = Date.now();

    const email =
      `jest${unique}@gmail.com`;

    const password = "Password@123";

    const phone =
      `98765${unique.toString().slice(-5)}`;

    // ======================================
    // Register
    // ======================================

    const registerResponse =
      await request(app)
        .post("/api/v1/customers/register")
        .send({
          name: "Jest User",
          email,
          password,
          phone,
        });

    expect([200, 201]).toContain(
      registerResponse.statusCode
    );

    // ======================================
    // Get OTP generated by test environment
    // ======================================

    const otp =
      global.__TEST_VERIFICATION_OTPS__?.[email];

    expect(otp).toBeDefined();
    expect(otp).toMatch(/^\d{6}$/);

    // ======================================
    // Verify Email
    // ======================================

    const verificationResponse =
      await request(app)
        .post("/api/v1/customers/verify-email")
        .send({
          email,
          otp,
        });

    expect(
      verificationResponse.statusCode
    ).toBe(200);

    expect(
      verificationResponse.body.success
    ).toBe(true);

    expect(
      verificationResponse.body.data.isVerified
    ).toBe(true);

    delete global.__TEST_VERIFICATION_OTPS__[email];

    // ======================================
    // Login
    // ======================================

    const response =
      await request(app)
        .post("/api/v1/customers/login")
        .send({
          email,
          password,
        });

    console.log(response.body);

    expect(response.statusCode).toBe(200);

    expect(response.body.success).toBe(true);

    expect(
      response.body.data
    ).toHaveProperty("accessToken");
  });
});


